inherit_from: .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 60

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 200

Metrics/ModuleLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/models/*
    - app/serializers/*
    - app/mailers/*

AllCops:
  Exclude:
    - spec/**/*
    - db/schema.rb
    - db/*
    - db/migrate/*
    - config/**
